// <auto-generated />
namespace WebApplicationFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FightsContextv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FightsContextv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191644487_FightsContext-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
